# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_data',
            name='Catagory',
            field=models.CharField(choices=[('Child-Labour', 'Child-labour'), ('Sex-Traffick', 'Sex-traffick')], max_length=100),
        ),
    ]
