# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_data',
            name='Catagory',
        ),
        migrations.AddField(
            model_name='report_data',
            name='about_issue',
            field=models.CharField(choices=[('Child-Labour', 'Child-labour'), ('Sex-Traffick', 'Sex-traffick'), ('Forced-Worker', 'Forced-worker')], default='Child-Labour', max_length=100),
        ),
        migrations.AddField(
            model_name='report_data',
            name='received_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
